# Generated by Django 5.1.2 on 2026-09-01 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edu_prenair', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseannouncement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_prenair.course'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_subcategories', to='edu_prenair.coursecategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='category_l_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_l_1', to='edu_prenair.coursecategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='category_l_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_l_2', to='edu_prenair.coursecategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='category_l_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_l_3', to='edu_prenair.coursecategory'),
        ),
        migrations.AddField(
            model_name='courserating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_prenair.course'),
        ),
        migrations.AddField(
            model_name='courserating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursewishlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_prenair.course'),
        ),
        migrations.AddField(
            model_name='coursewishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='edu_prenair.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='edu_prenair.module'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='edu_prenair.course'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_prenair.quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='edu_prenair.quiz'),
        ),
        migrations.AddField(
            model_name='quizquestionresponse',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_prenair.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizquestionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_prenair.quizquestion'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='questions',
            field=models.ManyToManyField(through='edu_prenair.QuizQuestionResponse', to='edu_prenair.quizquestion'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='completed_by_students', to='edu_prenair.lesson'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='edu_prenair.course'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='courserating',
            unique_together={('course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='coursewishlist',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='quizquestionresponse',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('user', 'course')},
        ),
    ]
