# Generated by Django 5.1.2 on 2026-09-01 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funnel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funnel',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='visited_funnels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funnellead',
            name='funnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='dashboard.funnel'),
        ),
        migrations.AddField(
            model_name='funnelorder',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funnelorder',
            name='funnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.funnel'),
        ),
        migrations.AddField(
            model_name='funnelproduct',
            name='funnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dashboard.funnel'),
        ),
        migrations.AddField(
            model_name='funnelorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.funnelproduct'),
        ),
        migrations.AddField(
            model_name='funnelstep',
            name='funnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='dashboard.funnel'),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard.templatecategory'),
        ),
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='dashboard.templatecategory'),
        ),
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['timestamp'], name='dashboard_t_timesta_51451b_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['country'], name='dashboard_t_country_e6581c_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['client_ip'], name='dashboard_t_client__28cb9b_idx'),
        ),
        migrations.AddField(
            model_name='userwebsite',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.template'),
        ),
        migrations.AddField(
            model_name='userwebsite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funnelstep',
            name='user_website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userwebsite'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL),
        ),
    ]
