# Generated by Django 5.1.2 on 2026-09-16 20:04

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_customuser_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(choices=profiles.models.available_timezone_choices, default='UTC', max_length=32),
        ),
    ]
