# Generated by Django 5.1.2 on 2026-09-01 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], default=1)),
                ('awarded_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='work_prenair_category_images/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='work_prenair.category')),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='work_prenair_gig_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('top_rated', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('basic_name', models.CharField(default='Basic', max_length=100)),
                ('basic_description', models.TextField()),
                ('basic_delivery_time', models.PositiveIntegerField(help_text='Delivery time in days')),
                ('basic_revisions', models.PositiveIntegerField(default=1)),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('standard_name', models.CharField(default='Standard', max_length=100)),
                ('standard_description', models.TextField()),
                ('standard_delivery_time', models.PositiveIntegerField(help_text='Delivery time in days')),
                ('standard_revisions', models.PositiveIntegerField(default=2)),
                ('standard_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_name', models.CharField(default='Premium', max_length=100)),
                ('premium_description', models.TextField()),
                ('premium_delivery_time', models.PositiveIntegerField(help_text='Delivery time in days')),
                ('premium_revisions', models.PositiveIntegerField(default=3)),
                ('premium_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category_level_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gigs_level_1', to='work_prenair.category')),
                ('category_level_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gigs_level_2', to='work_prenair.category')),
                ('category_level_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gigs_level_3', to='work_prenair.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='gigs', to='work_prenair.tag')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('delivery_time', models.PositiveIntegerField(help_text='Delivery time in days')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_offers', to=settings.AUTH_USER_MODEL)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_offers', to='work_prenair.gig')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField(blank=True, help_text='Client must submit requirements before order becomes active.', null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('package_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('custom_offer', 'Custom Offer')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending_requirements', 'Pending Requirements'), ('active', 'Active'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='pending_requirements', max_length=30)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_days', models.PositiveIntegerField(default=0)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('has_client_reviewed', models.BooleanField(default=False)),
                ('has_seller_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='work_prenair.gig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='work_prenair_deliveries/')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='work_prenair.order')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('is_client_review', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_work_reviews', to='work_prenair.gig')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_review', to='work_prenair.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='work_prenair.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
