"""
Django settings for prenair project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
# OPENAI_API_KEY is set properly below in the API keys section
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ASGI_APPLICATION = 'prenair.asgi.application'

ALLOWED_HOSTS = ['*']

# Base URL for generating absolute image URLs in API responses
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')


SITE_ID = 1

AUTH_USER_MODEL = "profiles.CustomUser"

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

EXTERNAL_APPS = [
    "channels",
    "fcm_django",
    "dashboard",
    "profiles",
    "digi_prenair",
    "edu_prenair",
    "commu_prenair",
    "work_prenair",
    "home",
    ### REST API APPS
    'rest_framework',
    "core_api",
    'rest_framework.authtoken', 
    'rest_framework_simplejwt',

    # Third-party apps
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

INSTALLED_APPS += EXTERNAL_APPS


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # standard django backend
    "allauth.account.auth_backends.AuthenticationBackend",  # all auth backend
]

MIDDLEWARE = [
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "prenair.middleware.UserTimezoneMiddleware",
    "prenair.middleware.UserLanguageMiddleware",
    "prenair.middleware.AdminAccessMiddleware",
    "prenair.middleware.AnalyticsMiddleware",
    "prenair.middleware.SubdomainRoutingMiddleware",
    
]

ROOT_URLCONF = "prenair.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "digi_prenair.context_processors.unread_notification_count",
                "dashboard.context_processors.digiprenair_upload_context",
                "django.template.context_processors.i18n",
            ],
        },
    },
]


# WSGI_APPLICATION = "prenair.wsgi.application"
ASGI_APPLICATION = "prenair.asgi.application"
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [(os.getenv('REDIS_HOST'))],
#         },
#     },
# }


LOGIN_URL = "/?login"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME'),
#         'USER': os.getenv('DB_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD'),
#         'HOST': os.getenv('DB_HOST'),
#         'PORT': os.getenv('DB_PORT'),
#         'OPTIONS': {
#             'connect_timeout': 30,
#         },
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


LANGUAGES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('it', 'Italian'),
    ('zh-hans', 'Chinese'), 
    ('ko', 'Korean'),
    ('nl', 'Dutch'),
]

LOCALE_PATHS = ( os.path.join(BASE_DIR, 'locale'), )




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_ROOT = BASE_DIR / "static/images"
MEDIA_URL = "/images/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

USE_S3_STORAGE = False


LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_ADAPTER = 'profiles.adapters.CustomSocialAccountAdapter'
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["email", "profile"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

# # General allauth settings
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # Disable username field
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_UNIQUE_EMAIL = True
# ACCOUNT_AUTHENTICATION_METHOD = "email"
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_EMAIL_VERIFICATION = "optional"  # Set to "mandatory" if needed

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET")

# Social account adapter
# SOCIALACCOUNT_ADAPTER = 'profiles.adapters.CustomSocialAccountAdapter'
# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'APP': {
#             'client_id': SOCIAL_AUTH_GOOGLE_OAUTH2_KEY,
#             'secret': SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET,
#             'key': ''
#         }
#     }
# }


STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET_COURSE = os.getenv("STRIPE_WEBHOOK_SECRET_COURSE")
STRIPE_WEBHOOK_SECRET_GIG_ORDER = os.getenv("STRIPE_WEBHOOK_SECRET_GIG_ORDER")
STRIPE_WEBHOOK_SECRET_PRODUCT = os.getenv("STRIPE_WEBHOOK_SECRET_PRODUCT")
STRIPE_WEBHOOK_SECRET_SUBSCRIBE = os.getenv("STRIPE_WEBHOOK_SECRET_SUBSCRIBE")

GROQ_API_KEY = os.getenv("GROQ_API")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
LEONARDO_API_KEY = os.getenv("LEONARDO_API_KEY")

PAYPAL_CLIENT_ID = os.getenv("PAYPAL_CLIENT_ID")
PAYPAL_CLIENT_SECRET = os.getenv("PAYPAL_CLIENT_SECRET")
PAYPAL_MODE = "sandbox"


# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.sendgrid.net"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
# DEFAULT_FROM_EMAIL = 'support@fireprenair.com'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'support@fireprenair.com'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER







#### configurations for Rest Apis
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access CSRF cookies
CSRF_COOKIE_SAMESITE = 'Lax'  # Or 'None' if cross-site requests
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.0.105:8000',
    'http://10.0.2.2:8000',
    'http://18.188.41.235',
]
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # Set True for production (HTTPS)



from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Ensures that only authenticated users can access the API
    ],
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=90),  # Adjust as needed
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),     # Adjust as needed
    "ROTATE_REFRESH_TOKENS": False,                   # Issue new refresh token on use
    "BLACKLIST_AFTER_ROTATION": True,                # Blacklist old refresh tokens
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,  # Use Django's SECRET_KEY or another secure key
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_COOKIE": "access_token",  # Optional: Store token in cookies
    "AUTH_COOKIE_REFRESH": "refresh_token",
    "AUTH_COOKIE_SECURE": False,   # Set to True if using HTTPS
    "AUTH_COOKIE_HTTP_ONLY": True, # Prevent JavaScript access
    "AUTH_COOKIE_SAMESITE": "Lax", # Adjust as needed
}
SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Store sessions in DB
SESSION_COOKIE_AGE = 604800  
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request
SESSION_COOKIE_SECURE = False  # Set to True if using HTTPS
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


GEOIP_PATH = os.path.join(BASE_DIR, 'geoip')


# ── FCM (Firebase Cloud Messaging) ───────────────────────────────────────
FCM_DJANGO_SETTINGS = {
    "DEFAULT_AUTO_HANDLE_TIMEOUT": 30,
    "DEFAULT_AUTO_RETRY_ATTEMPTS": 3,
}

# FCM uses a service account JSON file for server-side push.
# For local dev we skip it; the push helper is a no-op until the
# file is placed at fcm_service_account.json in the project root.
import json as _json
_fcm_cred = BASE_DIR / "fcm_service_account.json"
if _fcm_cred.exists():
    import firebase_admin
    from firebase_admin import credentials
    _cred = credentials.Certificate(str(_fcm_cred))
    firebase_admin.initialize_app(_cred)

